AllCops:
  Exclude:
    - '**/tmp/**/*'
    - '**/script/**/*'
    - Rakefile
    - Gemfile
  UseCache: true
  TargetRubyVersion: 2.5

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Metrics/BlockLength:
  Enabled: false


# You can generally fit two splits/panes side by side plus a navigator window
# on a 1920x1080 display, using a decent font size (14px or 16px) as long as
# there's a 80 char limit.
Metrics/LineLength:
  Max: 80

# Based on "How Long Can a Routine Be?" from Code Complete 2, which specifies
# 200 lines as a limit, adjusted for the the Ruby language, which is a lot
# more terse than Java or C++.
Metrics/MethodLength:
  Max: 30

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/GuardClause:
  Enabled: false

# By default Rubocop checks for literals, but since JRuby has immutable strings,
# all literals are already frozen.
Style/MutableConstant:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/SymbolArray:
  EnforcedStyle: brackets

Style/SymbolProc:
  Enabled: false
